name: 'Terraform Manual Operations'

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select action to perform'
        required: true
        type: choice
        options:
          - apply
          - destroy

env:
  TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
  TF_VAR_tenant_id: ${{ secrets.TENANT_ID }}
  TF_VAR_client_id: ${{ secrets.CLIENT_ID }}
  TF_VAR_client_secret: ${{ secrets.CLIENT_SECRET }}
  TF_VAR_vm_username: ${{ secrets.VM_USERNAME }}
  TF_VAR_vm_password: ${{ secrets.VM_PASSWORD }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Debug - Show Current Directory
      run: |
        pwd
        ls -la
        
    - name: Debug - Show Lab Directory
      run: |
        cd lab_08
        pwd
        ls -la

    - name: Terraform Init
      run: |
        cd lab_08
        terraform init

    - name: Terraform Apply
      if: github.event.inputs.action == 'apply'
      run: |
        cd lab_08
        terraform plan
        terraform apply -auto-approve

    - name: Terraform Destroy
      if: github.event.inputs.action == 'destroy'
      run: |
        cd lab_08
        terraform plan -destroy
        terraform destroy -auto-approve