name: 'Terraform Manual Operations'

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select action to perform'
        required: true
        type: choice
        options:
          - apply
          - destroy

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  ARM_ACCESS_KEY: ${{ secrets.STORAGE_ACCESS_KEY }}
  TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
  TF_VAR_tenant_id: ${{ secrets.TENANT_ID }}
  TF_VAR_client_id: ${{ secrets.CLIENT_ID }}
  TF_VAR_client_secret: ${{ secrets.CLIENT_SECRET }}
  TF_VAR_vm_username: ${{ secrets.VM_USERNAME }}
  TF_VAR_vm_password: ${{ secrets.VM_PASSWORD }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: |
        cd lab_08
        terraform init

    - name: Force Unlock State
      run: |
        cd lab_08
        terraform force-unlock -force 04769035-fc3e-acbd-2df0-6e1ab4fff7a6

    - name: Terraform Apply
      if: github.event.inputs.action == 'apply'
      run: |
        cd lab_08
        terraform plan -input=false
        terraform apply -auto-approve -input=false

    - name: Terraform Destroy
      if: github.event.inputs.action == 'destroy'
      run: |
        cd lab_08
        terraform plan -destroy -input=false
        terraform destroy -auto-approve -input=false

    - name: Cleanup Lock (if exists)
      if: always()
      continue-on-error: true
      run: |
        cd lab_08
        terraform force-unlock -force 04769035-fc3e-acbd-2df0-6e1ab4fff7a6